import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from '../contexts/LanguageContext';
import { LoadingProvider } from '../contexts/LoadingContext';
import { ToastProvider } from '../contexts/ToastContext';
import LayoutContent from '../components/LayoutContent';
import LoadingController from '../components/LoadingController';
import Navbar from "@/components/Navbar";
import ToastContainer from "@/components/ToastContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <ToastProvider>
          <LoadingProvider>
            <LanguageProvider>
              <LoadingController />
              <Navbar/>
              <LayoutContent>{children}</LayoutContent>
              <ToastContainer />
            </LanguageProvider>
          </LoadingProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
